backend:
  name: git-gateway

local_backend: true

media_folder: public/assets/images
public_folder: /assets/images

collections:
  - name: 'meta'
    label: 'Meta'
    files:
      - name: 'settings'
        label: 'Settings'
        file: '_meta/settings.json'
        fields:
          - name: 'blogger_name'
            title: 'Blogger Name'
            widget: 'string'
          - name: 'blogger_description'
            title: 'Blogger Description'
            widget: 'text'
          - name: 'blogger_photo'
            title: 'Blogger Photo'
            widget: 'image'
            required: false
          - name: 'blogger_social_contacts'
            label: 'Blogger Social Contacts'
            widget: 'list'
            fields:
              - name: 'icon_prefix'
                title: 'Icon Prefix'
                widget: 'string'
              - name: 'icon_name'
                title: 'Icon Name'
                widget: 'string'
              - name: 'link'
                title: 'link'
                widget: 'string'
          - name: 'copyright_text'
            title: 'Copyright Text'
            widget: 'markdown'
          - name: 'meta_keywords'
            title: 'Meta Keywords'
            widget: 'text'
          - name: 'default_social_image'
            title: 'Default Social Image'
            widget: 'image'
          - name: 'pagination_size'
            title: 'Pagination Size'
            widget: 'number'
      - name: 'navigation'
        label: 'Navigation'
        file: '_meta/navigation.json'
        fields:
          - name: 'menu_items'
            label: 'Menu Items'
            widget: 'list'
            fields:
              - name: 'title'
                title: 'Title'
                widget: 'string'
              - name: 'link'
                title: 'Link'
                widget: 'string'
  - name: 'pages'
    label: 'Pages'
    folder: '_pages'
    extension: 'mdx'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Date Published'
        name: 'date_published'
        widget: 'datetime'
      - label: 'Date Modified'
        name: 'date_modified'
        widget: 'datetime'
      - label: 'SEO Description'
        name: 'seo_description'
        widget: 'text'
      - label: 'SEO Keywords'
        name: 'seo_keywords'
        widget: 'list'
      - label: 'SEO Image'
        name: 'seo_image'
        widget: 'image'
        required: false
  - name: 'posts'
    label: 'Posts'
    folder: '_posts'
    extension: 'mdx'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Date Published'
        name: 'date_published'
        widget: 'datetime'
      - label: 'Date Modified'
        name: 'date_modified'
        widget: 'datetime'
      - label: 'SEO Keywords'
        name: 'seo_keywords'
        widget: 'list'
      - label: 'SEO Image'
        name: 'seo_image'
        widget: 'image'
        required: false
